firstName = input('First Name: ')
middleName = input('Middle Name: ')
lastName = input('Surname: ')
stateOfOrigin = input('State of Origin: ')
location = input('Address: ')
stateOfResidence = input('State of Residence: ')
maritalStatus = input('Marital Status: ')
employmentStatus = input('Status of Employment: ')
occupation = input('Occupation: ')

print('Hello! Mr. ' + firstName, middleName, lastName)
print('From ' + stateOfOrigin)
print('Living in ' + location)
print(stateOfResidence)
print(maritalStatus)
print(employmentStatus)
print(occupation)